name: Go

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Get dependencies
        run: go mod download
      - name: Check module is ready
        run: go mod tidy
      - name: Verify module
        run: go mod verify
      - name: Test
        run: go test -v ./...
